version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FLASK_ENV=production
    container_name: cicd-demo-app
    restart: unless-stopped

volumes:
  app_data:
